sudo: required

language: python

services:
  - docker

before_install:
- docker pull continuumio/anaconda

script:
- docker run -v $PWD:/wodpy_latest continuumio/anaconda /bin/bash -c "cd /wodpy_latest; nosetests tests/*.py"