name: unit_testing

on:
  pull_request:
    branches:
      - "main"

jobs:
  test:
    runs-on: ubuntu-latest
    container: iquod/wodpy:test-base-230716
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: run_tests
        run: pytest 